// @generated by packages/errors/gen-rust.ts — DO NOT EDIT BY HAND.
//
// Mirror of the canonical error codes. Source of truth: the @pl-graph/errors
// const object in packages/errors/src/index.ts. Regenerate with
// `bun run gen:rust` in packages/errors; the error-codes.gen drift test fails
// if this file is stale.
//
// The **string is the contract** (it crosses the FFI boundary verbatim), so the
// JS side matches `error.code === ErrorCode::*.as_str()` with no shared binary
// ABI. Never reuse or repurpose a value once shipped.

/// Canonical, stable error codes shared with the TypeScript packages.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(dead_code)] // not every code is thrown from Rust yet; the contract is shared regardless.
pub enum ErrorCode {
    /// A query/text parse or lex failure (GQL / Gremlin / `.pg`).
    Syntax,
    /// Input wasn't valid JSON.
    InvalidJson,
    /// Input parsed but didn't match the expected document shape.
    InvalidShape,
    /// An unknown serialization format name.
    UnknownFormat,
    /// A value outside the LPG property-value model.
    InvalidValue,
    /// An edge (or operation) referenced a vertex id that doesn't exist.
    MissingVertex,
    /// An invalid graph mutation (e.g. a cycle, a self-reference).
    InvalidGraphOp,
    /// An invalid tree structure or operation.
    InvalidTree,
    /// A recognized-but-not-yet-implemented feature.
    NotImplemented,
    /// A feature/clause/predicate that isn't supported.
    Unsupported,
    /// An unknown function/step/symbol referenced in a query.
    UnknownFunction,
    /// A failure crossing the native/wasm FFI boundary.
    Ffi,
}

impl ErrorCode {
    /// Every code, for exhaustiveness checks and the cross-language conformance test.
    pub const ALL: &'static [ErrorCode] = &[
        ErrorCode::Syntax,
        ErrorCode::InvalidJson,
        ErrorCode::InvalidShape,
        ErrorCode::UnknownFormat,
        ErrorCode::InvalidValue,
        ErrorCode::MissingVertex,
        ErrorCode::InvalidGraphOp,
        ErrorCode::InvalidTree,
        ErrorCode::NotImplemented,
        ErrorCode::Unsupported,
        ErrorCode::UnknownFunction,
        ErrorCode::Ffi,
    ];

    /// The stable `E_*` wire string. This is what crosses the FFI boundary.
    pub const fn as_str(&self) -> &'static str {
        match self {
            ErrorCode::Syntax => "E_SYNTAX",
            ErrorCode::InvalidJson => "E_INVALID_JSON",
            ErrorCode::InvalidShape => "E_INVALID_SHAPE",
            ErrorCode::UnknownFormat => "E_UNKNOWN_FORMAT",
            ErrorCode::InvalidValue => "E_INVALID_VALUE",
            ErrorCode::MissingVertex => "E_MISSING_VERTEX",
            ErrorCode::InvalidGraphOp => "E_INVALID_GRAPH_OP",
            ErrorCode::InvalidTree => "E_INVALID_TREE",
            ErrorCode::NotImplemented => "E_NOT_IMPLEMENTED",
            ErrorCode::Unsupported => "E_UNSUPPORTED",
            ErrorCode::UnknownFunction => "E_UNKNOWN_FUNCTION",
            ErrorCode::Ffi => "E_FFI",
        }
    }
}
